#ifndef DEFINITIONS_H
#define DEFINITIONS_H

// RenderQueue
#define RQ_MAX_SPRITE 2000
#define RQ_MAX_STATIC_MESH 2000
#define RQ_MAX_DYNAMIC_MESH 2000
#define RQ_MAX_POINT_LIGHT 500
#define RQ_MAX_DIRECTIONAL_LIGHT 100

#endif